### ISSUE TITLE
Spawn new player

### ISSUE THREAD

**Issue by Kas-2** [tremwil/CatalystAPI#1]
Hey! I know this project hasn't been modified in like 5 or 6 years, but, I was wondering if you could make a feature that you can spawn new objects(maybe even new Faith's?)

I am asking this, because I am trying to make a multiplayer mod.
If you make the feature, I hope you can also make that you can actually modify that position.

**Comment by tremwil** [comment]
Hi! Sadly, my knowledge about ME:C and its engine are quite limited, and I have no idea how one would even do this. Even if I could do it, I've lost interest in this project since a few years and don't plan to work on it again. 

I think if you can find someone who has experience with modding the Frostbite 3 engine, they might know how to do something like that.

**Comment by Kas-2** [comment]
> Hi! Sadly, my knowledge about ME:C and its engine are quite limited, and I have no idea how one would even do this. Even if I could do it, I've lost interest in this project since a few years and don't plan to work on it again.
> 
> I think if you can find someone who has experience with modding the Frostbite 3 engine, they might know how to do something like that.

Woah, didn't expect a response so fast.
Anyway, thanks for the reply, especially so quickly.

It's sad that DICE didn't provide a proper API, since the community could do a lot of great stuff.

Thanks anyway for your time.
